In [1]:
import pandas as pd
df = pd.read_csv(r"homeprices.csv")
df.head(20)

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [2]:
dummies = pd.get_dummies(df.town)
dummies.head(20)

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [3]:
merged = pd.concat([df,dummies],axis = 'columns')
merged.head()

              town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000             True        False         False
1  monroe township  3000  565000             True        False         False
2  monroe township  3200  610000             True        False         False
3  monroe township  3600  680000             True        False         False
4  monroe township  4000  725000             True        False         False

In [4]:
#Remove the town column to avoid producing dummy variable trap that messes up the model

final = merged.drop(['town','west windsor'],axis='columns')
final.head()

   area   price  monroe township  robinsville
0  2600  550000             True        False
1  3000  565000             True        False
2  3200  610000             True        False
3  3600  680000             True        False
4  4000  725000             True        False

In [5]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [6]:
model

LinearRegression()

In [7]:
x= final.drop('price',axis='columns')
x

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [8]:
y= final.price

In [9]:
model.fit(x,y)

LinearRegression()

In [10]:
model.predict([[3400,0,1]])

c:\Users\varsv\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([666914.10449365])

In [11]:
model.predict([[2800,0,0]])

c:\Users\varsv\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([605103.20361213])

In [12]:
model.predict([[400,0,1]])

c:\Users\varsv\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([286221.78026236])

In [13]:
model.predict([[3400,0,0]])

c:\Users\varsv\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [14]:
model.score(x,y)

0.9573929037221873

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
dfle= df
#monroe is 0, robbinsville is 1, west windsor is 2
dfle.town = le.fit_transform(dfle.town)
dfle.head()

   town  area   price
0     0  2600  550000
1     0  3000  565000
2     0  3200  610000
3     0  3600  680000
4     0  4000  725000

In [17]:
x= dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [18]:
y = dfle.price

y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers = [
        ('encoder',OneHotEncoder(sparse_output = False),[0])
    ],
    remainder = 'passthrough'
)

In [23]:
X=ct.fit_transform(x)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [24]:
X= X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [25]:
 model.fit(X,y)
 model.predict([[1,0,2800]])

array([590775.63964739])

In [27]:
model.predict([[0,1,3400]])

array([681241.6684584])

In [28]:
#Exercise 
import pandas as pd
df = pd.read_csv(r"carprices.csv")
df.head()

  Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [34]:
#Need to plot a scatter plot between price and mileage
from matplotlib import pyplot as plt
plt.scatter(df.Mileage,df['SellPrice($)'] )
plt.show()

KeyError: 'SellPrice($)'

In [ ]:
# Key Takeaways - One-Hot Encoding

## Summary of Methods Covered:

| Method | Pros | Cons |
|--------|------|------|
| **pd.get_dummies()** | Simple, quick for exploration | Not ideal for production pipelines |
| **LabelEncoder** | Simple integer encoding | Implies ordinal relationship (problematic for linear models) |
| **ColumnTransformer + OneHotEncoder** | Production-ready, integrates with sklearn pipelines | Slightly more verbose |

## Important Concepts:

1. **Dummy Variable Trap**: Always drop one category to avoid perfect multicollinearity
2. **Reference Category**: The dropped category becomes the baseline for interpretation
3. **Feature vs Target**: Always separate X (features) from y (target) before training

## When to Use What:
- **Linear Models**: Use One-Hot Encoding (avoid Label Encoding)
- **Tree-based Models**: Can use either (trees handle ordinal encoding well)
- **Production**: Use ColumnTransformer for reproducible pipelines

*Last updated: February 21, 2026*